### PR TITLE
regenerate package-lock to fix CI; fix compiler warnings

### PR DESCRIPTION
**Pull request by claytonrcarter**
Just seeing if this fixes CI, and update a couple of compiler warnings.

### CODE REVIEW

**Comment by claytonrcarter** [comment]
@mikehaertl the compiler is also saying that `skip_single_space()` (in `src/scanner.c`) is an unused function. Do you have impending plans for that, or can it be removed?

Also, CI does indeed seem to work! (Well, except for Windows, go figure.)

**Comment by mikehaertl** [comment]
> Do you have impending plans for that, or can it be removed?

I forgot to remove it. But I have more cleanup in that file anyway. PR coming soon.

BTW did you notice the slightly different path to `scanner.c` in `package.json` (`./src` instead of `src/`)? Could this be causing the failing test?

**Comment by claytonrcarter** [comment]
OK, no big deal. No the windows failure started as `stat` not being available (or at least different from the `stat` I'm used to) but now appears to be failing in earnest w/ parse errors and such.

**Comment by mikehaertl** [comment]
Hmm, could this be due to the removed `\r` stuff? `\r` also appears in the php parser a couple of times. Maybe I need to add this back in. This also requires updates in the scanner.

**Comment by claytonrcarter** [comment]
Ah, maybe yes. Does github let you see the windows CI logs on this? Some of the failures are pretty basic, like "Docblock w/ no tags". Anyway, I'm going to merge this and we can work on cleaning up Windows later.

Thank you again!

**Comment by mikehaertl** [comment]
> Does github let you see the windows CI logs on this?

Yup, seems fine now. Will have a look later. (Side rant: Life as a developer could be so easy withouth this weirdly designed system from Redmond :P)

**Pull request merged**
